<?php

if (!class_exists('WordPress_Style_It')) {

    /**
     * Main / front controller class
     */
    class WordPress_Style_It extends WPSI_Module
    {
        protected static $readable_properties = array(); // These should really be constants, but PHP doesn't allow class constants to be arrays
        protected static $writeable_properties = array();
        protected $modules;

        const VERSION = '0.1';
        const PREFIX = 'wpsi_';
        const DEBUG_MODE = false;


        /*
         * Magic methods
         */

        /**
         * Constructor
         *
         * @mvc Controller
         */
        protected function __construct()
        {
            $this->register_hook_callbacks();

            $this->modules = array(
                'WPSI_Settings' => WPSI_Settings::get_instance()
            );
        }


        /*
         * Static methods
         */

        /**
         * Enqueues CSS, JavaScript, etc
         *
         * @mvc Controller
         */
        public static function load_resources()
        {
            wp_register_script(
                self::PREFIX . 'wp-style-it',
                plugins_url('javascript/wp-style-it.js', dirname(__FILE__)),
                array('jquery'),
                self::VERSION,
                true
            );

            wp_register_script(
                self::PREFIX . 'wp-style-it-admin',
                plugins_url('javascript/wp-style-it-admin.js', dirname(__FILE__)),
                array('jquery'),
                self::VERSION,
                true
            );

            wp_register_script(
                self::PREFIX . 'edit-area',
                plugins_url('edit_area/edit_area_full.js', dirname(__FILE__)),
                array(),
                self::VERSION,
                true
            );

            wp_register_style(
                self::PREFIX . 'admin',
                plugins_url('css/admin.css', dirname(__FILE__)),
                array(),
                self::VERSION,
                'all'
            );

            if (is_admin()) {
                wp_enqueue_style(self::PREFIX . 'admin');
                wp_enqueue_script(self::PREFIX . 'wp-style-it-admin');
                wp_enqueue_script(self::PREFIX . 'edit-area');
            } else {
                wp_enqueue_script(self::PREFIX . 'wp-style-it');
            }
        }

        /**
         * Clears caches of content generated by caching plugins like WP Super Cache
         *
         * @mvc Model
         */
        protected static function clear_caching_plugins()
        {
            // WP Super Cache
            if (function_exists('wp_cache_clear_cache')) {
                wp_cache_clear_cache();
            }

            // W3 Total Cache
            if (class_exists('W3_Plugin_TotalCacheAdmin')) {
                $w3_total_cache = w3_instance('W3_Plugin_TotalCacheAdmin');

                if (method_exists($w3_total_cache, 'flush_all')) {
                    $w3_total_cache->flush_all();
                }
            }
        }


        /*
         * Instance methods
         */

        /**
         * Prepares sites to use the plugin during single or network-wide activation
         *
         * @mvc Controller
         *
         * @param bool $network_wide
         */
        public function activate($network_wide)
        {
            global $wpdb;

            if (function_exists('is_multisite') && is_multisite()) {
                if ($network_wide) {
                    $blogs = $wpdb->get_col("SELECT blog_id FROM $wpdb->blogs");

                    foreach ($blogs as $blog) {
                        switch_to_blog($blog);
                        $this->single_activate($network_wide);
                    }

                    restore_current_blog();
                } else {
                    $this->single_activate($network_wide);
                }
            } else {
                $this->single_activate($network_wide);
            }
        }

        /**
         * Runs activation code on a new WPMS site when it's created
         *
         * @mvc Controller
         *
         * @param int $blog_id
         */
        public function activate_new_site($blog_id)
        {
            switch_to_blog($blog_id);
            $this->single_activate(true);
            restore_current_blog();
        }

        /**
         * Prepares a single blog to use the plugin
         *
         * @mvc Controller
         *
         * @param bool $network_wide
         */
        protected function single_activate($network_wide)
        {
            foreach ($this->modules as $module) {
                $module->activate($network_wide);
            }
        }

        /**
         * Rolls back activation procedures when de-activating the plugin
         *
         * @mvc Controller
         */
        public function deactivate()
        {
            foreach ($this->modules as $module) {
                $module->deactivate();
            }
        }

        /**
         * Register callbacks for actions and filters
         *
         * @mvc Controller
         */
        public function register_hook_callbacks()
        {
            add_action('wpmu_new_blog', __CLASS__ . '::activate_new_site');
            add_action('wp_enqueue_scripts', __CLASS__ . '::load_resources');
            add_action('admin_enqueue_scripts', __CLASS__ . '::load_resources');

            add_action('init', array($this, 'init'));
            add_action('init', array($this, 'upgrade'), 11);

            add_action('wp_head', array($this, 'injectCss'), 9999);
        }

        public function get_suppress_post_id($options)
        {
            $suppress_post_id = array();

            foreach (explode(',', $options['suppress-post-id']) as $id) {
                $id2 = explode('-', $id);
                if (count($id2) == 1) {
                    array_push($suppress_post_id, $id2[0]);
                } else {
                    for ($i = $id2[0]; $i <= $id2[1]; $i++) {
                        array_push($suppress_post_id, $i);
                    }
                }
            }
            return $suppress_post_id;
        }

        public function get_suppress_url($options)
        {
            $suppress_url = array();

            foreach (explode(',', $options['suppress-url']) as $id) {
                array_push($suppress_url, $id);
            }
            return $suppress_url;
        }

        public function get_suppress_ipaddress($options)
        {
            $suppress_ipaddress = array();

            foreach (explode(',', $options['suppress-ipaddress']) as $id) {
                array_push($suppress_ipaddress, $id);
            }
            return $suppress_ipaddress;
        }

        public function get_suppress_referrer($options)
        {
            $suppress_referrer = array();

            foreach (explode(',', $options['suppress-referrer']) as $id) {
                array_push($suppress_referrer, $id);
            }
            return $suppress_referrer;
        }

        private function to_int_array($array_in)
        {
            $array_out = array();

            if (isset($array_in) && is_array($array_in)) {
                foreach ($array_in as $id) {
                    array_push($array_out, intval($id));
                }
            }
            return $array_out;
        }

        public function get_suppress_category($options)
        {
            return $this->to_int_array($options['suppress-category']);
        }

        public function get_suppress_tag($options)
        {
            return $this->to_int_array($options['suppress-tag']);
        }

        public function get_suppress_user($options)
        {
            return $this->to_int_array($options['suppress-user']);
        }

        public function get_suppress_format($options)
        {
            return $options['suppress-format'];
        }

        public function get_suppress_post_type($options)
        {
            return $options['suppress-post-type'];
        }

        public function get_suppress_language($options)
        {
            return $options['suppress-language'];
        }

        public function in_array_substr($needle, $haystack)
        {
            foreach ($haystack as $hay_item) {
                if ($hay_item !== "" && strpos($needle, $hay_item)) {
                    return true;
                }
            }
            return false;
        }

        public function is_suppress_specific($options, $content)
        {
            $suppress_post_id = $this->get_suppress_post_id($options);
            $suppress_category = $this->get_suppress_category($options);
            $suppress_tag = $this->get_suppress_tag($options);
            $suppress_user = $this->get_suppress_user($options);
            $suppress_format = $this->get_suppress_format($options);
            $suppress_post_type = $this->get_suppress_post_type($options);
            $suppress_language = $this->get_suppress_language($options);
            $suppress_url = $this->get_suppress_url($options);
            $suppress_referrer = $this->get_suppress_referrer($options);
            $suppress_ipaddress = $this->get_suppress_ipaddress($options);

            return ((count($suppress_format) > 0 && in_array(get_post_format(), $suppress_format))
                || (count($suppress_user) > 0 && in_array(get_the_author_meta('ID'), $suppress_user))
                || (count($suppress_tag) > 0 && has_tag($suppress_tag))
                || (count($suppress_category) > 0 && has_category($suppress_category))
                || (count($suppress_post_type) > 0 && in_array(get_post_type(get_the_ID()), $suppress_post_type))
                || (count($suppress_language) > 0 && function_exists('qtrans_getLanguage') && in_array(qtrans_getLanguage(), $suppress_language))
                || (count($suppress_url) > 0 && $this->in_array_substr(get_the_permalink(), $suppress_url))
                || (count($suppress_referrer) > 0 && $this->in_array_substr($_SERVER['HTTP_REFERER'], $suppress_referrer))
                || (count($suppress_ipaddress) > 0 && $this->in_array_substr($_SERVER['REMOTE_ADDR'], $suppress_ipaddress))
                || (!is_feed() && in_array(get_the_ID(), $suppress_post_id))
                || (!is_feed() && strpos($content, '<!--NoAds-->') !== false)
                || (!is_feed() && strpos($content, '<!--NoWidgetAds-->') !== false)
                || (is_single() && $options['suppress-on-posts'] == 1)
                || (is_page() && $options['suppress-on-pages'] == 1)
                || (is_attachment() && $options['suppress-on-attachment'] == 1)
                || (is_category() && $options['suppress-on-category'] == 1)
                || (is_tag() && $options['suppress-on-tag'] == 1)
                || (is_home() && $options['suppress-on-home'] == 1)
                || (is_front_page() && $options['suppress-on-front'] == 1)
                || (is_archive() && $options['suppress-on-archive'] == 1)
                || (is_author() && $options['suppress-on-author'] == 1)
                || (is_404() && $options['suppress-on-error'] == 1)
                || (function_exists('bnc_wptouch_is_mobile') && bnc_wptouch_is_mobile() && $options['suppress-on-wptouch'] == 1)
                || (is_user_logged_in() && $options['suppress-on-logged-in'] == 1)
            );
        }

        public function compressCss($code)
        {
            $code = preg_replace("/(?:\/\*(?:.|\n|\r|\t)*?(?:\*\/|$))/s", "", $code);
            $code = preg_replace('/(( |\t|\r)*\n( |\t)*)+/s', "", $code);
            $code = preg_replace('/( |\t|\r)?(\:|,|\{|\})( |\t|\r)+/', "$2", $code);
            return $code;
        }

        public function injectCss()
        {
            $content = get_the_content();

            $options = $this->modules['WPSI_Settings']->settings['options'];

            if ($this->is_suppress_specific($options, $content)) {
                return;
            }

            $style = $this->modules['WPSI_Settings']->settings['blocks']['code'];

            if (!empty($style)) {
                ?>
                <style type="text/css"><?php echo $this->compressCss($style); ?></style>
            <?php
            }

        }

        /**
         * Initializes variables
         *
         * @mvc Controller
         */
        public function init()
        {
            try {
            } catch (Exception $exception) {
                add_notice(__METHOD__ . ' error: ' . $exception->getMessage(), 'error');
            }
        }

        /**
         * Checks if the plugin was recently updated and upgrades if necessary
         *
         * @mvc Controller
         *
         * @param string $db_version
         */
        public function upgrade($db_version = 0)
        {
            if (version_compare($this->modules['WPSI_Settings']->settings['db-version'], self::VERSION, '==')) {
                return;
            }

            foreach ($this->modules as $module) {
                $module->upgrade($this->modules['WPSI_Settings']->settings['db-version']);
            }

            $this->modules['WPSI_Settings']->settings = array('db-version' => self::VERSION);
            self::clear_caching_plugins();
        }

        /**
         * Checks that the object is in a correct state
         *
         * @mvc Model
         *
         * @param string $property An individual property to check, or 'all' to check all of them
         * @return bool
         */
        protected function is_valid($property = 'all')
        {
            return true;
        }
    }

    ; // end WordPress_Style_It
}
